"""
Specifies reusable names of data columns.
"""


class Keys:
    DATE = "Date"
    LOAD = "Load"
    LOAD_BASE = "Load_Base"
    LOAD_BEFORE_FLEXIBILITY = "Load_Before_Flexibility"
    LOAD_HEAT_PUMPS = "Load_Heat_Pumps"
    LOAD_EVS = "Load_EVs"
    HEAT_DEMAND = "Heat_Demand_MW"
    """Hourly heat demand, similarly to electricity in MWt."""
    HEAT_FLEXIBLE_PRODUCTION = "Heat_Flexible"
    """Hourly heat production (from flexible sources), in MWt."""
    HEAT_P2H_PRODUCTION = "Heat_P2H"
    """Hourly heat production from power-to-heat technologies, in MWt."""
    IMPORT = "Import"
    EXPORT = "Export"
    NET_IMPORT = "Net_Import"
    PRODUCTION = "Production"
    TEMPERATURE = "Temperature"

    SOLAR = "Solar"
    WIND = "Wind"
    WIND_ONSHORE = "Wind onshore"
    WIND_OFFSHORE = "Wind offshore"

    COAL = "Coal"
    GAS = "Gas"
    OIL = "Oil"

    NUCLEAR = "Nuclear"
    BIOMASS = "Biomass"
    HYDRO = "Hydro"
    HYDRO_INFLOW_PONDAGE = "Hydro pondage inflow"
    HYDRO_INFLOW_ROR = "Hydro RoR inflow"
    HYDRO_INFLOW_RESERVOIR = "Hydro reservoir inflow"
    HYDRO_INFLOW_PUMPED_OPEN = "Hydro pumped open inflow"
    HYDRO_PUMPED_STORAGE = "Hydro pumped storage"
    GEOTHERMAL = "Geothermal"
    OTHER = "Other"

    PRICE = "Price"
    PRICE_CURRENCY = "Price_Currency"
    PRICE_EXPORT = "Price_Export"
    PRICE_IMPORT = "Price_Import"
    PRICE_TYPE = "Price_Type"
    SHADOW_PRICE = "Shadow_Price"
